apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8081
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 632aad60.argoproj.io
