spec: 
  template:
    spec:
      containers:
      - name: argocd-server
        volumeMounts:
        - name: extensions
          mountPath: /tmp/extensions/
      - name: argocd-extensions
        image: rbreeze/argocd-extensions
        volumeMounts:
        - name: extensions
          mountPath: /tmp/extensions/
      volumes:
      - name: extensions
        emptyDir: {}