apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: applications.argoproj.io
    app.kubernetes.io/part-of: argocd
  name: applications.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: ArgoCDExtension
    plural: ArgoCDExtensions
    shortNames:
      - extension
      - extensions
    singular: extension
  scope: Namespaced
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["respository", "revision"]
          properties:
            repository:
              type: "string"
              minimum: 1
            revision:
              type: "string"
              minimum: 1
  versions:
    - name: v1alpha1
      served: true
      storage: true
