---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: argocd-server-extensions-role
rules:
  - apiGroups:
      - extension.argoproj.io
    resources:
      - argocdextensions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extension.argoproj.io
    resources:
      - argocdextensions/finalizers
    verbs:
      - update
  - apiGroups:
      - extension.argoproj.io
    resources:
      - argocdextensions/status
    verbs:
      - get
      - patch
      - update
